version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: corn-frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - default

networks:
  default:
    driver: bridge
